# Constants
PACKAGE = group_chat
HOST = localIpAddr
PORT = 20020
SERVER = server
CLIENT = client

up.server:
	python3 -m $(PACKAGE) $(SERVER) $(HOST) $(PORT)

up.client:
	python3 -m $(PACKAGE) $(CLIENT) $(HOST) $(PORT)
